services:
    postgresql:
        image: postgres:15.4
        restart: always
        container_name: congraduation-psql-container
        ports:
            - '5435:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
        volumes:
            - ./init:/docker-entrypoint-initdb.d/
